generate_pgm_from_keyframes:
  ros__parameters:
    input:
      keyframe_pcd_dir: /home/zry/Code/vina_slam_ws/data/map/UGP_route2/keyFrames
      pose_file: /home/zry/Code/vina_slam_ws/data/map/UGP_route2/keyFrames/alidarState.txt
    output:
      directory: /home/zry/Code/vina_slam_ws/data/map/test/UGP_route2/occupancy
      pgm_filename: map.pgm
      yaml_filename: map.yaml
    projection:
      esti_floor: false
      lidar_height: 0.15
      floor_height: -0.15
      min_th_floor: 0.05
      max_th_floor: 2.0
      usable_scan_range: 50.0
      grid_map_resolution: 0.05
      occupancy_ratio: 0.3
      log_odds_hit: 0.85
      log_odds_miss: -0.4
      log_odds_max: 3.5
      log_odds_min: -2.0
    map_yaml:
      negate: 0
      occupied_thresh: 0.65
      free_thresh: 0.25
